-- GENERATED FILE. DO NOT EDIT BY HAND.
-- Source: scripts/db/seed-data.mjs
-- Regenerate: npm run db:seed:sql
-- Prerequisite: run scripts/db/migrate.mjs or npm run db:migrate first.
-- Rows: 6 groups, 64 rules, 70 thresholds, 66 conditions.

SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO app_config (`key`, `value`)
VALUES
  ('campaign_name', 'Sony Badge Pilot'),
  ('badge_rules_version', '2026-07-20-confirmed-badge-rules-001'),
  ('support_message', 'Please contact Sony Thailand support if badge data looks incorrect.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO badge_display_groups (
  group_code, badge_type, display_name, sort_order, is_active
)
VALUES
  ('full-frame-camera', 'product', 'Full Frame Camera', 10, TRUE),
  ('prime-lens', 'product', 'Prime Lens', 20, TRUE),
  ('wide-normal-zoom-lens', 'product', 'Wide & Normal Zoom Lens', 30, TRUE),
  ('telephoto-super-telephoto-lens', 'product', 'Telephoto & Super Telephoto Lens', 40, TRUE),
  ('macro-lens', 'product', 'Macro Lens', 50, TRUE),
  ('quest', 'quest', 'Quest Badge', 100, TRUE)
ON DUPLICATE KEY UPDATE
  badge_type = VALUES(badge_type),
  display_name = VALUES(display_name),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);
DELETE FROM badge_display_groups WHERE group_code NOT IN ('full-frame-camera', 'prime-lens', 'wide-normal-zoom-lens', 'telephoto-super-telephoto-lens', 'macro-lens', 'quest');

INSERT INTO badge_rules (
  badge_code, badge_name, badge_type, rule_type, display_category, display_group,
  display_group_code, product_model_code, product_url, description, sort_order,
  is_active, active_from, active_to, registration_start, registration_end
)
VALUES
  ('product-sel100m28gm', 'SEL100M28GM', 'product', 'achievement', 'Product Badge', 'macro-lens', 'macro-lens', 'SEL100M28GM', NULL, 'Register SEL100M28GM to unlock this Product Badge.', 1, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel90m28g', 'SEL90M28G', 'product', 'achievement', 'Product Badge', 'macro-lens', 'macro-lens', 'SEL90M28G', NULL, 'Register SEL90M28G to unlock this Product Badge.', 2, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel30m35', 'SEL30M35', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL30M35', NULL, 'Register SEL30M35 to unlock this Product Badge.', 101, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel135f18gm', 'SEL135F18GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL135F18GM', NULL, 'Register SEL135F18GM to unlock this Product Badge.', 102, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel14f18gm', 'SEL14F18GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL14F18GM', NULL, 'Register SEL14F18GM to unlock this Product Badge.', 103, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel16f18g', 'SEL16F18G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL16F18G', NULL, 'Register SEL16F18G to unlock this Product Badge.', 104, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel20f18g', 'SEL20F18G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL20F18G', NULL, 'Register SEL20F18G to unlock this Product Badge.', 105, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24f14gm', 'SEL24F14GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL24F14GM', NULL, 'Register SEL24F14GM to unlock this Product Badge.', 106, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24f28g', 'SEL24F28G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL24F28G', NULL, 'Register SEL24F28G to unlock this Product Badge.', 107, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel35f14gm', 'SEL35F14GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL35F14GM', NULL, 'Register SEL35F14GM to unlock this Product Badge.', 108, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel35f18f', 'SEL35F18F', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL35F18F', NULL, 'Register SEL35F18F to unlock this Product Badge.', 109, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50f12gm', 'SEL50F12GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50F12GM', NULL, 'Register SEL50F12GM to unlock this Product Badge.', 110, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50f14gm', 'SEL50F14GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50F14GM', NULL, 'Register SEL50F14GM to unlock this Product Badge.', 111, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50m28', 'SEL50M28', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50M28', NULL, 'Register SEL50M28 to unlock this Product Badge.', 112, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel85f14gm', 'SEL85F14GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL85F14GM', NULL, 'Register SEL85F14GM to unlock this Product Badge.', 113, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel85f14gm2', 'SEL85F14GM2', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL85F14GM2', NULL, 'Register SEL85F14GM2 to unlock this Product Badge.', 114, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1655g', 'SEL1655G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1655G', NULL, 'Register SEL1655G to unlock this Product Badge.', 201, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel55210', 'SEL55210', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL55210', NULL, 'Register SEL55210 to unlock this Product Badge.', 202, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp18110g', 'SELP18110G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP18110G', NULL, 'Register SELP18110G to unlock this Product Badge.', 203, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1625g', 'SEL1625G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1625G', NULL, 'Register SEL1625G to unlock this Product Badge.', 204, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635gm', 'SEL1635GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635GM', NULL, 'Register SEL1635GM to unlock this Product Badge.', 205, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635gm2', 'SEL1635GM2', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635GM2', NULL, 'Register SEL1635GM2 to unlock this Product Badge.', 206, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2070g', 'SEL2070G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2070G', NULL, 'Register SEL2070G to unlock this Product Badge.', 207, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24105g', 'SEL24105G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL24105G', NULL, 'Register SEL24105G to unlock this Product Badge.', 208, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2450g', 'SEL2450G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2450G', NULL, 'Register SEL2450G to unlock this Product Badge.', 209, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470gm', 'SEL2470GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470GM', NULL, 'Register SEL2470GM to unlock this Product Badge.', 210, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470gm2', 'SEL2470GM2', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470GM2', NULL, 'Register SEL2470GM2 to unlock this Product Badge.', 211, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2870gm', 'SEL2870GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2870GM', NULL, 'Register SEL2870GM to unlock this Product Badge.', 212, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50150gm', 'SEL50150GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL50150GM', NULL, 'Register SEL50150GM to unlock this Product Badge.', 213, TRUE, NULL, NULL, NULL, NULL),
  ('product-selc1635g', 'SELC1635G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELC1635G', NULL, 'Register SELC1635G to unlock this Product Badge.', 214, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp1635g', 'SELP1635G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP1635G', NULL, 'Register SELP1635G to unlock this Product Badge.', 215, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp28135g', 'SELP28135G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP28135G', NULL, 'Register SELP28135G to unlock this Product Badge.', 216, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635z', 'SEL1635Z', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635Z', NULL, 'Register SEL1635Z to unlock this Product Badge.', 217, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470z', 'SEL2470Z', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470Z', NULL, 'Register SEL2470Z to unlock this Product Badge.', 218, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70350g', 'SEL70350G', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70350G', NULL, 'Register SEL70350G to unlock this Product Badge.', 301, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel100400mc', 'SEL100400MC', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL100400MC', NULL, 'Register SEL100400MC to unlock this Product Badge.', 302, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel100400gm', 'SEL100400GM', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL100400GM', NULL, 'Register SEL100400GM to unlock this Product Badge.', 303, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel200600g', 'SEL200600G', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL200600G', NULL, 'Register SEL200600G to unlock this Product Badge.', 304, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel300f28gm', 'SEL300F28GM', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL300F28GM', NULL, 'Register SEL300F28GM to unlock this Product Badge.', 305, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel400800g', 'SEL400800G', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL400800G', NULL, 'Register SEL400800G to unlock this Product Badge.', 306, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel400f28gm', 'SEL400F28GM', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL400F28GM', NULL, 'Register SEL400F28GM to unlock this Product Badge.', 307, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel600f40gm', 'SEL600F40GM', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL600F40GM', NULL, 'Register SEL600F40GM to unlock this Product Badge.', 308, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200gm', 'SEL70200GM', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200GM', NULL, 'Register SEL70200GM to unlock this Product Badge.', 309, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200gm2', 'SEL70200GM2', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200GM2', NULL, 'Register SEL70200GM2 to unlock this Product Badge.', 310, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200g', 'SEL70200G', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200G', NULL, 'Register SEL70200G to unlock this Product Badge.', 311, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200g2', 'SEL70200G2', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200G2', NULL, 'Register SEL70200G2 to unlock this Product Badge.', 312, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-1m2', 'ILCE-1M2', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-1M2', NULL, 'Register ILCE-1M2 to unlock this Product Badge.', 401, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-9m3', 'ILCE-9M3', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-9M3', NULL, 'Register ILCE-9M3 to unlock this Product Badge.', 402, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7rm5', 'ILCE-7RM5', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7RM5', NULL, 'Register ILCE-7RM5 to unlock this Product Badge.', 403, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m5', 'ILCE-7M5', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M5', NULL, 'Register ILCE-7M5 to unlock this Product Badge.', 404, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m4', 'ILCE-7M4', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M4', NULL, 'Register ILCE-7M4 to unlock this Product Badge.', 405, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m3', 'ILCE-7M3', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M3', NULL, 'Register ILCE-7M3 to unlock this Product Badge.', 406, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7cm2', 'ILCE-7CM2', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7CM2', NULL, 'Register ILCE-7CM2 to unlock this Product Badge.', 407, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7c', 'ILCE-7C', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7C', NULL, 'Register ILCE-7C to unlock this Product Badge.', 408, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7cr', 'ILCE-7CR', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7CR', NULL, 'Register ILCE-7CR to unlock this Product Badge.', 409, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7sm3', 'ILCE-7SM3', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7SM3', NULL, 'Register ILCE-7SM3 to unlock this Product Badge.', 410, TRUE, NULL, NULL, NULL, NULL),
  ('portrait-master', 'Portrait Master', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible Portrait Master models.', 1000, TRUE, NULL, NULL, NULL, NULL),
  ('wide-architect', 'Wide Architect', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible Wide Architect models.', 1010, TRUE, NULL, NULL, NULL, NULL),
  ('the-visionary', 'The Visionary', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible The Visionary models.', 1020, TRUE, NULL, NULL, NULL, NULL),
  ('trinity-master', 'Trinity Master', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own one model from each required G Master family.', 1030, TRUE, NULL, NULL, NULL, NULL),
  ('trinity-junior', 'Trinity Junior', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own all three required Trinity Junior models.', 1040, TRUE, NULL, NULL, NULL, NULL),
  ('all-rounder', 'All Rounder', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own any three eligible All Rounder models.', 1050, TRUE, NULL, NULL, NULL, NULL),
  ('f2-master', 'F2 Master', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own both required F2 Master models.', 1060, TRUE, NULL, NULL, NULL, NULL),
  ('the-magnifier', 'The Magnifier', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own any one eligible macro model.', 1070, TRUE, NULL, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE
  badge_name = VALUES(badge_name),
  badge_type = VALUES(badge_type),
  rule_type = VALUES(rule_type),
  display_category = VALUES(display_category),
  display_group = VALUES(display_group),
  display_group_code = VALUES(display_group_code),
  product_model_code = VALUES(product_model_code),
  product_url = VALUES(product_url),
  description = VALUES(description),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active),
  active_from = VALUES(active_from),
  active_to = VALUES(active_to),
  registration_start = VALUES(registration_start),
  registration_end = VALUES(registration_end);
DELETE FROM badge_rules WHERE badge_code NOT IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier');

DELETE FROM badge_rule_thresholds
WHERE badge_rule_id IN (SELECT id FROM badge_rules WHERE badge_code IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier'));
INSERT INTO badge_rule_thresholds (
  badge_rule_id, level, display_name, required_count, achieved_image_url,
  locked_image_url, share_image_url, sort_order
)
VALUES
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100m28gm'), 'achievement', 'SEL100M28GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 1),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel90m28g'), 'achievement', 'SEL90M28G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 2),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel30m35'), 'achievement', 'SEL30M35', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 101),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel135f18gm'), 'achievement', 'SEL135F18GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 102),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel14f18gm'), 'achievement', 'SEL14F18GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 103),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel16f18g'), 'achievement', 'SEL16F18G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 104),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel20f18g'), 'achievement', 'SEL20F18G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 105),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f14gm'), 'achievement', 'SEL24F14GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 106),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f28g'), 'achievement', 'SEL24F28G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 107),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f14gm'), 'achievement', 'SEL35F14GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 108),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f18f'), 'achievement', 'SEL35F18F', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 109),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f12gm'), 'achievement', 'SEL50F12GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 110),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f14gm'), 'achievement', 'SEL50F14GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 111),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50m28'), 'achievement', 'SEL50M28', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 112),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm'), 'achievement', 'SEL85F14GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 113),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm2'), 'achievement', 'SEL85F14GM2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 114),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1655g'), 'achievement', 'SEL1655G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 201),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel55210'), 'achievement', 'SEL55210', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 202),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp18110g'), 'achievement', 'SELP18110G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 203),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1625g'), 'achievement', 'SEL1625G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 204),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm'), 'achievement', 'SEL1635GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 205),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm2'), 'achievement', 'SEL1635GM2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 206),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2070g'), 'achievement', 'SEL2070G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 207),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24105g'), 'achievement', 'SEL24105G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 208),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2450g'), 'achievement', 'SEL2450G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 209),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm'), 'achievement', 'SEL2470GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 210),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm2'), 'achievement', 'SEL2470GM2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 211),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2870gm'), 'achievement', 'SEL2870GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 212),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50150gm'), 'achievement', 'SEL50150GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 213),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selc1635g'), 'achievement', 'SELC1635G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 214),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp1635g'), 'achievement', 'SELP1635G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 215),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp28135g'), 'achievement', 'SELP28135G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 216),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635z'), 'achievement', 'SEL1635Z', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 217),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470z'), 'achievement', 'SEL2470Z', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 218),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70350g'), 'achievement', 'SEL70350G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 301),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400mc'), 'achievement', 'SEL100400MC', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 302),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400gm'), 'achievement', 'SEL100400GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 303),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel200600g'), 'achievement', 'SEL200600G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 304),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel300f28gm'), 'achievement', 'SEL300F28GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 305),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400800g'), 'achievement', 'SEL400800G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 306),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400f28gm'), 'achievement', 'SEL400F28GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 307),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel600f40gm'), 'achievement', 'SEL600F40GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 308),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm'), 'achievement', 'SEL70200GM', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 309),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm2'), 'achievement', 'SEL70200GM2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 310),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g'), 'achievement', 'SEL70200G', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 311),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g2'), 'achievement', 'SEL70200G2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 312),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-1m2'), 'achievement', 'ILCE-1M2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 401),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-9m3'), 'achievement', 'ILCE-9M3', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 402),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7rm5'), 'achievement', 'ILCE-7RM5', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 403),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m5'), 'achievement', 'ILCE-7M5', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 404),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m4'), 'achievement', 'ILCE-7M4', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 405),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m3'), 'achievement', 'ILCE-7M3', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 406),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cm2'), 'achievement', 'ILCE-7CM2', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 407),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7c'), 'achievement', 'ILCE-7C', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 408),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cr'), 'achievement', 'ILCE-7CR', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 409),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7sm3'), 'achievement', 'ILCE-7SM3', 1, '/mock/my-product/badge-hero.svg', NULL, '/mock/my-product/badge-hero.svg', 410),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'bronze', 'Portrait Master Bronze', 2, '/mock/my-missions/tier-medal.svg', NULL, NULL, 1001),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'silver', 'Portrait Master Silver', 3, '/mock/my-missions/tier-shield.svg', NULL, NULL, 1002),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'gold', 'Portrait Master Gold', 4, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1003),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'bronze', 'Wide Architect Bronze', 3, '/mock/my-missions/tier-medal.svg', NULL, NULL, 1011),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'silver', 'Wide Architect Silver', 4, '/mock/my-missions/tier-shield.svg', NULL, NULL, 1012),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'gold', 'Wide Architect Gold', 5, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1013),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'bronze', 'The Visionary Bronze', 2, '/mock/my-missions/tier-medal.svg', NULL, NULL, 1021),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'silver', 'The Visionary Silver', 3, '/mock/my-missions/tier-shield.svg', NULL, NULL, 1022),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'gold', 'The Visionary Gold', 4, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1023),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'achievement', 'Trinity Master', 3, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1031),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-junior'), 'achievement', 'Trinity Junior', 3, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1041),
  ((SELECT id FROM badge_rules WHERE badge_code = 'all-rounder'), 'achievement', 'All Rounder', 3, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1051),
  ((SELECT id FROM badge_rules WHERE badge_code = 'f2-master'), 'achievement', 'F2 Master', 2, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1061),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-magnifier'), 'achievement', 'The Magnifier', 1, '/mock/my-missions/tier-frame.svg', NULL, NULL, 1071);

DELETE FROM badge_rule_conditions
WHERE badge_rule_id IN (SELECT id FROM badge_rules WHERE badge_code IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier'));
INSERT INTO badge_rule_conditions (
  badge_rule_id, condition_label, match_type, required_count, sony_skus
)
VALUES
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100m28gm'), 'Own SEL100M28GM', 'any', 1, '["SEL100M28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel90m28g'), 'Own SEL90M28G', 'any', 1, '["SEL90M28G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel30m35'), 'Own SEL30M35', 'any', 1, '["SEL30M35"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel135f18gm'), 'Own SEL135F18GM', 'any', 1, '["SEL135F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel14f18gm'), 'Own SEL14F18GM', 'any', 1, '["SEL14F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel16f18g'), 'Own SEL16F18G', 'any', 1, '["SEL16F18G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel20f18g'), 'Own SEL20F18G', 'any', 1, '["SEL20F18G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f14gm'), 'Own SEL24F14GM', 'any', 1, '["SEL24F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f28g'), 'Own SEL24F28G', 'any', 1, '["SEL24F28G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f14gm'), 'Own SEL35F14GM', 'any', 1, '["SEL35F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f18f'), 'Own SEL35F18F', 'any', 1, '["SEL35F18F"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f12gm'), 'Own SEL50F12GM', 'any', 1, '["SEL50F12GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f14gm'), 'Own SEL50F14GM', 'any', 1, '["SEL50F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50m28'), 'Own SEL50M28', 'any', 1, '["SEL50M28"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm'), 'Own SEL85F14GM', 'any', 1, '["SEL85F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm2'), 'Own SEL85F14GM2', 'any', 1, '["SEL85F14GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1655g'), 'Own SEL1655G', 'any', 1, '["SEL1655G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel55210'), 'Own SEL55210', 'any', 1, '["SEL55210"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp18110g'), 'Own SELP18110G', 'any', 1, '["SELP18110G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1625g'), 'Own SEL1625G', 'any', 1, '["SEL1625G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm'), 'Own SEL1635GM', 'any', 1, '["SEL1635GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm2'), 'Own SEL1635GM2', 'any', 1, '["SEL1635GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2070g'), 'Own SEL2070G', 'any', 1, '["SEL2070G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24105g'), 'Own SEL24105G', 'any', 1, '["SEL24105G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2450g'), 'Own SEL2450G', 'any', 1, '["SEL2450G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm'), 'Own SEL2470GM', 'any', 1, '["SEL2470GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm2'), 'Own SEL2470GM2', 'any', 1, '["SEL2470GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2870gm'), 'Own SEL2870GM', 'any', 1, '["SEL2870GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50150gm'), 'Own SEL50150GM', 'any', 1, '["SEL50150GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selc1635g'), 'Own SELC1635G', 'any', 1, '["SELC1635G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp1635g'), 'Own SELP1635G', 'any', 1, '["SELP1635G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp28135g'), 'Own SELP28135G', 'any', 1, '["SELP28135G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635z'), 'Own SEL1635Z', 'any', 1, '["SEL1635Z"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470z'), 'Own SEL2470Z', 'any', 1, '["SEL2470Z"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70350g'), 'Own SEL70350G', 'any', 1, '["SEL70350G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400mc'), 'Own SEL100400MC', 'any', 1, '["SEL100400MC"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400gm'), 'Own SEL100400GM', 'any', 1, '["SEL100400GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel200600g'), 'Own SEL200600G', 'any', 1, '["SEL200600G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel300f28gm'), 'Own SEL300F28GM', 'any', 1, '["SEL300F28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400800g'), 'Own SEL400800G', 'any', 1, '["SEL400800G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400f28gm'), 'Own SEL400F28GM', 'any', 1, '["SEL400F28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel600f40gm'), 'Own SEL600F40GM', 'any', 1, '["SEL600F40GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm'), 'Own SEL70200GM', 'any', 1, '["SEL70200GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm2'), 'Own SEL70200GM2', 'any', 1, '["SEL70200GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g'), 'Own SEL70200G', 'any', 1, '["SEL70200G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g2'), 'Own SEL70200G2', 'any', 1, '["SEL70200G2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-1m2'), 'Own ILCE-1M2', 'any', 1, '["ILCE-1M2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-9m3'), 'Own ILCE-9M3', 'any', 1, '["ILCE-9M3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7rm5'), 'Own ILCE-7RM5', 'any', 1, '["ILCE-7RM5"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m5'), 'Own ILCE-7M5', 'any', 1, '["ILCE-7M5"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m4'), 'Own ILCE-7M4', 'any', 1, '["ILCE-7M4"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m3'), 'Own ILCE-7M3', 'any', 1, '["ILCE-7M3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cm2'), 'Own ILCE-7CM2', 'any', 1, '["ILCE-7CM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7c'), 'Own ILCE-7C', 'any', 1, '["ILCE-7C"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cr'), 'Own ILCE-7CR', 'any', 1, '["ILCE-7CR"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7sm3'), 'Own ILCE-7SM3', 'any', 1, '["ILCE-7SM3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'Collect eligible Portrait Master models', 'min_count', 4, '["SEL35F14GM","SEL50F14GM","SEL50F12GM","SEL85F14GM","SEL85F14GM2","SEL100M28GM","SEL135F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'Collect eligible Wide Architect models', 'min_count', 5, '["SEL1224GM","SEL14F18GM","SEL16F18G","SEL20F18G","SEL1625G","SEL1635GM","SEL1635GM2","SEL1635Z","SEL2470GM","SEL2470GM2","SEL2450G","SELC1635G","SEL1655G","SEL2070G","SEL24105G","SEL2470Z","SEL24F14GM","SEL24F28G","SEL2870GM","SEL35F14GM","SEL35F18F","SELP1635G","SELP18110G","SELP28135G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'Collect eligible The Visionary models', 'min_count', 4, '["SEL100400GM","SEL400800G","SEL200600G","SEL300F28GM","SEL400F28GM","SEL600F40GM","SEL70350G","SEL55210","SEL100400MC"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 16-35 GM family model', 'any', 1, '["SEL1635GM","SEL1635GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 24-70 GM family model', 'any', 1, '["SEL2470GM","SEL2470GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 70-200 GM family model', 'any', 1, '["SEL70200GM","SEL70200GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-junior'), 'Own all Trinity Junior models', 'all', 3, '["SEL2450G","SEL1625G","SEL70200G2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'all-rounder'), 'Own any three All Rounder models', 'min_count', 3, '["SEL2070G","SELP1635G","SEL1635Z","SEL70200G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'f2-master'), 'Own both F2 Master models', 'all', 2, '["SEL2870GM","SEL50150GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-magnifier'), 'Own any one macro model', 'any', 1, '["SEL100M28GM","SEL90M28G","SEL50M28","SEL30M35"]');

COMMIT;
