export const appConfig = [
  ["campaign_name", "Sony Badge Pilot"],
  ["badge_rules_version", "2026-06-29-client-excel-001"],
  ["support_message", "Please contact Sony Thailand support if badge data looks incorrect."],
];

export const badgeRules = [
  ["ff-camera-owner", "Key FF Models", "product", "achievement", "Product ownership badge", "Key FF models", "Own one supported Sony full-frame camera body.", 10],
  ["key-lens-owner", "Key Lens Models", "product", "achievement", "Product ownership badge", "Key Lens models", "Own one supported Sony GM lens.", 20],
  ["portrait-master", "Portrait Master", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own any one Portrait Master lens from the client SKU list.", 30],
  ["wide-architect", "Wide Architect", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own any one Wide Architect lens from the client SKU list.", 40],
  ["the-visionary", "The Visionary", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own any one Sharp Shooter / The Visionary lens from the client SKU list.", 50],
  ["trinity-master", "Trinity Master", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own one 16-35 GM family lens, one 24-70 GM family lens, and one 70-200 GM family lens.", 60],
  ["trinity-active", "Trinity Active", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own all three Trinity Active lenses from the client SKU list.", 70],
  ["all-rounder", "All Rounder", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own any three of the four All Rounder lenses from the client SKU list.", 80],
  ["f2-master", "F2 Master", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own both F2 Master lenses from the client SKU list.", 90],
  ["the-magnifier", "The Magnifier", "quest", "achievement", "Achievement badge", "Client Excel quest rules", "Own any one macro lens from the client SKU list.", 100],
  ["alpha-body-collector", "Alpha Body Collector", "product", "tier", "Level badge demo", "10 product tier rules", "Collect eligible Alpha body products. Bronze 1, Silver 5, Gold 10.", 200],
  ["gm-lens-collector", "GM Lens Collector", "product", "tier", "Level badge demo", "10 product tier rules", "Collect eligible GM lens products. Bronze 1, Silver 5, Gold 10.", 210],
  ["creator-kit-collector", "Creator Kit Collector", "quest", "tier", "Level badge demo", "Shared SKU across many rules", "Collect eligible creator kit products. Bronze 1, Silver 5, Gold 10.", 220],
].map(([
  code,
  name,
  badgeType,
  ruleType,
  displayCategory,
  displayGroup,
  description,
  sortOrder,
]) => ({
  code,
  name,
  badgeType,
  ruleType,
  displayCategory,
  displayGroup,
  description,
  sortOrder,
  activeFrom: "2026-05-01",
  activeTo: null,
  registrationStart: "2026-05-01",
  registrationEnd: "2026-12-31",
}));

export const badgeThresholds = [
  ["ff-camera-owner", "achievement", "Key FF Models", 1, "https://placehold.co/240x240?text=FF", "https://placehold.co/240x240?text=Locked", 10],
  ["key-lens-owner", "achievement", "Key Lens Models", 1, "https://placehold.co/240x240?text=Lens", "https://placehold.co/240x240?text=Locked", 20],
  ["portrait-master", "achievement", "Portrait Master", 1, "https://placehold.co/240x240?text=Portrait", "https://placehold.co/240x240?text=Locked", 30],
  ["wide-architect", "achievement", "Wide Architect", 1, "https://placehold.co/240x240?text=Wide", "https://placehold.co/240x240?text=Locked", 40],
  ["the-visionary", "achievement", "The Visionary", 1, "https://placehold.co/240x240?text=Visionary", "https://placehold.co/240x240?text=Locked", 50],
  ["trinity-master", "achievement", "Trinity Master", 3, "https://placehold.co/240x240?text=Trinity", "https://placehold.co/240x240?text=Locked", 60],
  ["trinity-active", "achievement", "Trinity Active", 3, "https://placehold.co/240x240?text=Active", "https://placehold.co/240x240?text=Locked", 70],
  ["all-rounder", "achievement", "All Rounder", 3, "https://placehold.co/240x240?text=All+Rounder", "https://placehold.co/240x240?text=Locked", 80],
  ["f2-master", "achievement", "F2 Master", 2, "https://placehold.co/240x240?text=F2", "https://placehold.co/240x240?text=Locked", 90],
  ["the-magnifier", "achievement", "The Magnifier", 1, "https://placehold.co/240x240?text=Macro", "https://placehold.co/240x240?text=Locked", 100],
  ["alpha-body-collector", "bronze", "Body Bronze", 1, "https://placehold.co/240x240?text=Body+Bronze", "https://placehold.co/240x240?text=Locked", 201],
  ["alpha-body-collector", "silver", "Body Silver", 5, "https://placehold.co/240x240?text=Body+Silver", "https://placehold.co/240x240?text=Locked", 202],
  ["alpha-body-collector", "gold", "Body Gold", 10, "https://placehold.co/240x240?text=Body+Gold", "https://placehold.co/240x240?text=Locked", 203],
  ["gm-lens-collector", "bronze", "GM Bronze", 1, "https://placehold.co/240x240?text=GM+Bronze", "https://placehold.co/240x240?text=Locked", 211],
  ["gm-lens-collector", "silver", "GM Silver", 5, "https://placehold.co/240x240?text=GM+Silver", "https://placehold.co/240x240?text=Locked", 212],
  ["gm-lens-collector", "gold", "GM Gold", 10, "https://placehold.co/240x240?text=GM+Gold", "https://placehold.co/240x240?text=Locked", 213],
  ["creator-kit-collector", "bronze", "Creator Bronze", 1, "https://placehold.co/240x240?text=Creator+Bronze", "https://placehold.co/240x240?text=Locked", 221],
  ["creator-kit-collector", "silver", "Creator Silver", 5, "https://placehold.co/240x240?text=Creator+Silver", "https://placehold.co/240x240?text=Locked", 222],
  ["creator-kit-collector", "gold", "Creator Gold", 10, "https://placehold.co/240x240?text=Creator+Gold", "https://placehold.co/240x240?text=Locked", 223],
].map(([ruleCode, level, displayName, requiredCount, achievedImageUrl, lockedImageUrl, sortOrder]) => ({
  ruleCode,
  level,
  displayName,
  requiredCount,
  achievedImageUrl,
  lockedImageUrl,
  sortOrder,
}));

export const badgeConditions = [
  ["ff-camera-owner", "Own any key FF model", "any", 1, ["ILCE-1M2", "ILCE-9M3", "ILCE-7RM5", "ILCE-7M5", "ILCE-7CM2", "OTHER_FF"]],
  ["key-lens-owner", "Own any key lens model", "any", 1, ["SEL2470GM2", "SEL1635GM2", "SEL70200GM2", "SEL50F12GM", "SEL50F14GM", "SEL35F14GM", "SEL50150F2GM", "SEL2870F2GM", "OTHER_GM_LENS"]],
  ["portrait-master", "Own any one Portrait Master lens", "any", 1, ["SEL35F14GM", "SEL50F14GM", "SEL50F12GM", "SEL85F14GM", "SEL85F14GM2", "SEL135F18GM"]],
  ["wide-architect", "Own any one Wide Architect lens", "any", 1, ["SEL1224GM", "SEL14F18GM", "SEL16F18G", "SEL20F18G", "SEL1625G", "SEL1635GM", "SEL1635GM2", "SEL1635Z", "SEL2470GM", "SEL2470GM2", "SEL2450G", "SELC1635G", "SEL1655G", "SEL2070G", "SEL24105G", "SEL2470Z", "SEL24F14GM", "SEL24F28G", "SEL2870GM", "SEL35F14GM", "SEL35F18F", "SELP1635G", "SELP18110G", "SELP28135G"]],
  ["the-visionary", "Own any one Sharp Shooter / The Visionary lens", "any", 1, ["SEL100400GM", "SEL400800G", "SEL200600G", "SEL300F28GM", "SEL400F28GM", "SEL600F40GM"]],
  ["trinity-master", "Own one 16-35 GM family lens", "any", 1, ["SEL1635GM", "SEL1635GM2"]],
  ["trinity-master", "Own one 24-70 GM family lens", "any", 1, ["SEL2470GM", "SEL2470GM2"]],
  ["trinity-master", "Own one 70-200 GM family lens", "any", 1, ["SEL70200GM", "SEL70200GM2"]],
  ["trinity-active", "Own all Trinity Active lenses", "all", 3, ["SEL2450G", "SEL1625G", "SEL70200G2"]],
  ["all-rounder", "Own any three All Rounder lenses", "min_count", 3, ["SEL2070G", "SELP1635G", "SEL1635Z", "SEL70200G"]],
  ["f2-master", "Own both F2 Master lenses", "all", 2, ["SEL2870GM", "SEL50150GM"]],
  ["the-magnifier", "Own any one macro lens", "any", 1, ["SEL100M28GM", "SEL90M28G"]],
  ["alpha-body-collector", "Own Alpha tier demo products", "min_count", 10, ["SHARED-TIER-01", "BODY-SKU-02", "BODY-SKU-03", "BODY-SKU-04", "BODY-SKU-05", "BODY-SKU-06", "BODY-SKU-07", "BODY-SKU-08", "BODY-SKU-09", "BODY-SKU-10"]],
  ["gm-lens-collector", "Own GM tier demo products", "min_count", 10, ["SHARED-TIER-01", "GM-SKU-02", "GM-SKU-03", "GM-SKU-04", "GM-SKU-05", "GM-SKU-06", "GM-SKU-07", "GM-SKU-08", "GM-SKU-09", "GM-SKU-10"]],
  ["creator-kit-collector", "Own creator kit tier demo products", "min_count", 10, ["SHARED-TIER-01", "BODY-SKU-02", "BODY-SKU-03", "BODY-SKU-04", "BODY-SKU-05", "GM-SKU-02", "GM-SKU-03", "GM-SKU-04", "GM-SKU-05", "GM-SKU-06"]],
].map(([ruleCode, label, matchType, requiredCount, sonySkus]) => ({
  ruleCode,
  label,
  matchType,
  requiredCount,
  sonySkus,
}));
