-- GENERATED FILE. DO NOT EDIT BY HAND.
-- Source: scripts/db/seed-data.mjs
-- Regenerate: npm run db:seed:sql
-- Prerequisite: run scripts/db/migrate.mjs or npm run db:migrate first.
-- Rows: 6 groups, 64 rules, 70 thresholds, 66 conditions.

SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO app_config (`key`, `value`)
VALUES
  ('campaign_name', 'Sony Badge Pilot'),
  ('badge_rules_version', '2026-07-24-quest-badge-images-001'),
  ('support_message', 'Please contact Sony Thailand support if badge data looks incorrect.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO badge_display_groups (
  group_code, badge_type, display_name, sort_order, is_active
)
VALUES
  ('full-frame-camera', 'product', 'Full Frame Camera', 10, TRUE),
  ('prime-lens', 'product', 'Prime Lens', 20, TRUE),
  ('wide-normal-zoom-lens', 'product', 'Wide & Normal Zoom Lens', 30, TRUE),
  ('telephoto-super-telephoto-lens', 'product', 'Telephoto & Super Telephoto Lens', 40, TRUE),
  ('macro-lens', 'product', 'Macro Lens', 50, TRUE),
  ('quest', 'quest', 'Quest Badge', 100, TRUE)
ON DUPLICATE KEY UPDATE
  badge_type = VALUES(badge_type),
  display_name = VALUES(display_name),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);
DELETE FROM badge_display_groups WHERE group_code NOT IN ('full-frame-camera', 'prime-lens', 'wide-normal-zoom-lens', 'telephoto-super-telephoto-lens', 'macro-lens', 'quest');

INSERT INTO badge_rules (
  badge_code, badge_name, badge_type, rule_type, display_category, display_group,
  display_group_code, product_model_code, product_url, description, sort_order,
  is_active, active_from, active_to, registration_start, registration_end
)
VALUES
  ('product-sel100m28gm', 'FE 100 mm.F2.8 Macro GM OSS', 'product', 'achievement', 'Product Badge', 'macro-lens', 'macro-lens', 'SEL100M28GM', NULL, 'Register SEL100M28GM to unlock this Product Badge.', 1, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel90m28g', 'FE 90mm F2.8 Macro G OSS', 'product', 'achievement', 'Product Badge', 'macro-lens', 'macro-lens', 'SEL90M28G', NULL, 'Register SEL90M28G to unlock this Product Badge.', 2, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel30m35', 'E 30mm F3.5 Macro', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL30M35', NULL, 'Register SEL30M35 to unlock this Product Badge.', 101, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel135f18gm', 'FE 135mm F1.8 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL135F18GM', NULL, 'Register SEL135F18GM to unlock this Product Badge.', 102, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel14f18gm', 'FE 14mm F1.8 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL14F18GM', NULL, 'Register SEL14F18GM to unlock this Product Badge.', 103, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel16f18g', 'FE 16mm F1.8 G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL16F18G', NULL, 'Register SEL16F18G to unlock this Product Badge.', 104, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel20f18g', 'FE 20mm F1.8 G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL20F18G', NULL, 'Register SEL20F18G to unlock this Product Badge.', 105, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24f14gm', 'FE 24mm F1.4 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL24F14GM', NULL, 'Register SEL24F14GM to unlock this Product Badge.', 106, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24f28g', 'FE 24mm F2.8 G', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL24F28G', NULL, 'Register SEL24F28G to unlock this Product Badge.', 107, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel35f14gm', 'FE 35mm F1.4 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL35F14GM', NULL, 'Register SEL35F14GM to unlock this Product Badge.', 108, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel35f18f', 'FE 35mm F1.8', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL35F18F', NULL, 'Register SEL35F18F to unlock this Product Badge.', 109, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50f12gm', 'FE 50mm F1.2 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50F12GM', NULL, 'Register SEL50F12GM to unlock this Product Badge.', 110, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50f14gm', 'FE 50mm F1.4 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50F14GM', NULL, 'Register SEL50F14GM to unlock this Product Badge.', 111, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50m28', 'FE 50mm F2.8 Macro', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL50M28', NULL, 'Register SEL50M28 to unlock this Product Badge.', 112, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel85f14gm', 'FE 85mm F1.4 GM', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL85F14GM', NULL, 'Register SEL85F14GM to unlock this Product Badge.', 113, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel85f14gm2', 'FE 85mm F1.4 GM II', 'product', 'achievement', 'Product Badge', 'prime-lens', 'prime-lens', 'SEL85F14GM2', NULL, 'Register SEL85F14GM2 to unlock this Product Badge.', 114, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1655g', 'E 16-55mm F2.8 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1655G', NULL, 'Register SEL1655G to unlock this Product Badge.', 201, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel55210', 'E 55-210mm F4.5-6.3 OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL55210', NULL, 'Register SEL55210 to unlock this Product Badge.', 202, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp18110g', 'E PZ 18-110mm F4 G OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP18110G', NULL, 'Register SELP18110G to unlock this Product Badge.', 203, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1625g', 'FE 16-25mm F2.8 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1625G', NULL, 'Register SEL1625G to unlock this Product Badge.', 204, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635gm', 'FE 16-35mm F2.8 GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635GM', NULL, 'Register SEL1635GM to unlock this Product Badge.', 205, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635gm2', 'FE 16-35mm F2.8 GM II', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635GM2', NULL, 'Register SEL1635GM2 to unlock this Product Badge.', 206, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2070g', 'FE 20-70mm F4 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2070G', NULL, 'Register SEL2070G to unlock this Product Badge.', 207, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel24105g', 'FE 24-105mm F4 G OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL24105G', NULL, 'Register SEL24105G to unlock this Product Badge.', 208, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2450g', 'FE 24-50mm F2.8 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2450G', NULL, 'Register SEL2450G to unlock this Product Badge.', 209, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470gm', 'FE 24-70mm F2.8 GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470GM', NULL, 'Register SEL2470GM to unlock this Product Badge.', 210, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470gm2', 'FE 24-70mm F2.8 GM II', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470GM2', NULL, 'Register SEL2470GM2 to unlock this Product Badge.', 211, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2870gm', 'FE 28-70mm F2 GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2870GM', NULL, 'Register SEL2870GM to unlock this Product Badge.', 212, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel50150gm', 'FE 50-150 mm.F2 GM', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL50150GM', NULL, 'Register SEL50150GM to unlock this Product Badge.', 213, TRUE, NULL, NULL, NULL, NULL),
  ('product-selc1635g', 'FE C 16-35mm T3.1 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELC1635G', NULL, 'Register SELC1635G to unlock this Product Badge.', 214, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp1635g', 'FE PZ 16-35mm F4 G', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP1635G', NULL, 'Register SELP1635G to unlock this Product Badge.', 215, TRUE, NULL, NULL, NULL, NULL),
  ('product-selp28135g', 'FE PZ 28-135mm F4 G OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SELP28135G', NULL, 'Register SELP28135G to unlock this Product Badge.', 216, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel1635z', 'Vario-Tessar T* FE 16-35mm F4 ZA OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL1635Z', NULL, 'Register SEL1635Z to unlock this Product Badge.', 217, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel2470z', 'Vario-Tessar T* FE 24-70mm F4 ZA OSS', 'product', 'achievement', 'Product Badge', 'wide-normal-zoom-lens', 'wide-normal-zoom-lens', 'SEL2470Z', NULL, 'Register SEL2470Z to unlock this Product Badge.', 218, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70350g', 'E 70-350mm F4.5-6.3 G OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70350G', NULL, 'Register SEL70350G to unlock this Product Badge.', 301, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel100400mc', 'FE 100-400 mm.F4.5 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL100400MC', NULL, 'Register SEL100400MC to unlock this Product Badge.', 302, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel100400gm', 'FE 100-400mm F4.5-5.6 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL100400GM', NULL, 'Register SEL100400GM to unlock this Product Badge.', 303, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel200600g', 'FE 200-600mm F5.6-6.3 G OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL200600G', NULL, 'Register SEL200600G to unlock this Product Badge.', 304, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel300f28gm', 'FE 300mm F2.8 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL300F28GM', NULL, 'Register SEL300F28GM to unlock this Product Badge.', 305, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel400800g', 'FE 400-800 mm.F6.3-8 G OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL400800G', NULL, 'Register SEL400800G to unlock this Product Badge.', 306, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel400f28gm', 'FE 400mm F2.8 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL400F28GM', NULL, 'Register SEL400F28GM to unlock this Product Badge.', 307, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel600f40gm', 'FE 600mm F4 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL600F40GM', NULL, 'Register SEL600F40GM to unlock this Product Badge.', 308, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200gm', 'FE 70-200mm F2.8 GM OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200GM', NULL, 'Register SEL70200GM to unlock this Product Badge.', 309, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200gm2', 'FE 70-200mm F2.8 GM OSS II', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200GM2', NULL, 'Register SEL70200GM2 to unlock this Product Badge.', 310, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200g', 'FE 70-200mm F4 G OSS', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200G', NULL, 'Register SEL70200G to unlock this Product Badge.', 311, TRUE, NULL, NULL, NULL, NULL),
  ('product-sel70200g2', 'FE 70-200mm F4 Macro G OSS II', 'product', 'achievement', 'Product Badge', 'telephoto-super-telephoto-lens', 'telephoto-super-telephoto-lens', 'SEL70200G2', NULL, 'Register SEL70200G2 to unlock this Product Badge.', 312, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-1m2', 'Alpha 1 II', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-1M2', NULL, 'Register ILCE-1M2 to unlock this Product Badge.', 401, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-9m3', 'Alpha 9 III', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-9M3', NULL, 'Register ILCE-9M3 to unlock this Product Badge.', 402, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7rm5', 'Alpha 7R V', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7RM5', NULL, 'Register ILCE-7RM5 to unlock this Product Badge.', 403, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m5', 'Alpha 7 V', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M5', NULL, 'Register ILCE-7M5 to unlock this Product Badge.', 404, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m4', 'Alpha 7 IV', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M4', NULL, 'Register ILCE-7M4 to unlock this Product Badge.', 405, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7m3', 'Alpha 7 III', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7M3', NULL, 'Register ILCE-7M3 to unlock this Product Badge.', 406, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7cm2', 'Alpha 7C II', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7CM2', NULL, 'Register ILCE-7CM2 to unlock this Product Badge.', 407, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7c', 'Alpha 7C', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7C', NULL, 'Register ILCE-7C to unlock this Product Badge.', 408, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7cr', 'Alpha 7CR', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7CR', NULL, 'Register ILCE-7CR to unlock this Product Badge.', 409, TRUE, NULL, NULL, NULL, NULL),
  ('product-ilce-7sm3', 'Alpha 7S III', 'product', 'achievement', 'Product Badge', 'full-frame-camera', 'full-frame-camera', 'ILCE-7SM3', NULL, 'Register ILCE-7SM3 to unlock this Product Badge.', 410, TRUE, NULL, NULL, NULL, NULL),
  ('portrait-master', 'Portrait Master', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible Portrait Master models.', 1000, TRUE, NULL, NULL, NULL, NULL),
  ('wide-architect', 'Wide Architect', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible Wide Architect models.', 1010, TRUE, NULL, NULL, NULL, NULL),
  ('the-visionary', 'The Visionary', 'quest', 'tier', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Collect unique eligible The Visionary models.', 1020, TRUE, NULL, NULL, NULL, NULL),
  ('trinity-master', 'Trinity Master', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own one model from each required G Master family.', 1030, TRUE, NULL, NULL, NULL, NULL),
  ('trinity-junior', 'Trinity Junior', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own all three required Trinity Junior models.', 1040, TRUE, NULL, NULL, NULL, NULL),
  ('all-rounder', 'All Rounder', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own any three eligible All Rounder models.', 1050, TRUE, NULL, NULL, NULL, NULL),
  ('f2-master', 'F2 Master', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own both required F2 Master models.', 1060, TRUE, NULL, NULL, NULL, NULL),
  ('the-magnifier', 'The Magnifier', 'quest', 'achievement', 'Quest Badge', 'quest', 'quest', NULL, NULL, 'Own any one eligible macro model.', 1070, TRUE, NULL, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE
  badge_name = VALUES(badge_name),
  badge_type = VALUES(badge_type),
  rule_type = VALUES(rule_type),
  display_category = VALUES(display_category),
  display_group = VALUES(display_group),
  display_group_code = VALUES(display_group_code),
  product_model_code = VALUES(product_model_code),
  product_url = VALUES(product_url),
  description = VALUES(description),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active),
  active_from = VALUES(active_from),
  active_to = VALUES(active_to),
  registration_start = VALUES(registration_start),
  registration_end = VALUES(registration_end);
DELETE FROM badge_rules WHERE badge_code NOT IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier');

DELETE FROM badge_rule_thresholds
WHERE badge_rule_id IN (SELECT id FROM badge_rules WHERE badge_code IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier'));
INSERT INTO badge_rule_thresholds (
  badge_rule_id, level, display_name, required_count, achieved_image_url,
  locked_image_url, share_image_url, sort_order
)
VALUES
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100m28gm'), 'achievement', 'FE 100 mm.F2.8 Macro GM OSS', 1, '/product-badge/SEL100M28GM.png', NULL, '/product-badge/SEL100M28GM.png', 1),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel90m28g'), 'achievement', 'FE 90mm F2.8 Macro G OSS', 1, '/product-badge/SEL90M28G.png', NULL, '/product-badge/SEL90M28G.png', 2),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel30m35'), 'achievement', 'E 30mm F3.5 Macro', 1, '/product-badge/SEL30M35.png', NULL, '/product-badge/SEL30M35.png', 101),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel135f18gm'), 'achievement', 'FE 135mm F1.8 GM', 1, '/product-badge/SEL135F18GM.png', NULL, '/product-badge/SEL135F18GM.png', 102),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel14f18gm'), 'achievement', 'FE 14mm F1.8 GM', 1, '/product-badge/SEL14F18GM.png', NULL, '/product-badge/SEL14F18GM.png', 103),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel16f18g'), 'achievement', 'FE 16mm F1.8 G', 1, '/product-badge/SEL16F18G.png', NULL, '/product-badge/SEL16F18G.png', 104),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel20f18g'), 'achievement', 'FE 20mm F1.8 G', 1, '/product-badge/SEL20F18G.png', NULL, '/product-badge/SEL20F18G.png', 105),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f14gm'), 'achievement', 'FE 24mm F1.4 GM', 1, '/product-badge/SEL24F14GM.png', NULL, '/product-badge/SEL24F14GM.png', 106),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f28g'), 'achievement', 'FE 24mm F2.8 G', 1, '/product-badge/SEL24F28G.png', NULL, '/product-badge/SEL24F28G.png', 107),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f14gm'), 'achievement', 'FE 35mm F1.4 GM', 1, '/product-badge/SEL35F14GM.png', NULL, '/product-badge/SEL35F14GM.png', 108),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f18f'), 'achievement', 'FE 35mm F1.8', 1, '/product-badge/SEL35F18F.png', NULL, '/product-badge/SEL35F18F.png', 109),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f12gm'), 'achievement', 'FE 50mm F1.2 GM', 1, '/product-badge/SEL50F12GM.png', NULL, '/product-badge/SEL50F12GM.png', 110),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f14gm'), 'achievement', 'FE 50mm F1.4 GM', 1, '/product-badge/SEL50F14GM.png', NULL, '/product-badge/SEL50F14GM.png', 111),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50m28'), 'achievement', 'FE 50mm F2.8 Macro', 1, '/product-badge/SEL50M28.png', NULL, '/product-badge/SEL50M28.png', 112),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm'), 'achievement', 'FE 85mm F1.4 GM', 1, '/product-badge/SEL85F14GM.png', NULL, '/product-badge/SEL85F14GM.png', 113),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm2'), 'achievement', 'FE 85mm F1.4 GM II', 1, '/product-badge/SEL85F14GM2.png', NULL, '/product-badge/SEL85F14GM2.png', 114),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1655g'), 'achievement', 'E 16-55mm F2.8 G', 1, '/product-badge/SEL1655G.png', NULL, '/product-badge/SEL1655G.png', 201),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel55210'), 'achievement', 'E 55-210mm F4.5-6.3 OSS', 1, '/product-badge/SEL55210.png', NULL, '/product-badge/SEL55210.png', 202),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp18110g'), 'achievement', 'E PZ 18-110mm F4 G OSS', 1, '/product-badge/SELP18110G.png', NULL, '/product-badge/SELP18110G.png', 203),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1625g'), 'achievement', 'FE 16-25mm F2.8 G', 1, '/product-badge/SEL1625G.png', NULL, '/product-badge/SEL1625G.png', 204),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm'), 'achievement', 'FE 16-35mm F2.8 GM', 1, '/product-badge/SEL1635GM.png', NULL, '/product-badge/SEL1635GM.png', 205),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm2'), 'achievement', 'FE 16-35mm F2.8 GM II', 1, '/product-badge/SEL1635GM2.png', NULL, '/product-badge/SEL1635GM2.png', 206),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2070g'), 'achievement', 'FE 20-70mm F4 G', 1, '/product-badge/SEL2070G.png', NULL, '/product-badge/SEL2070G.png', 207),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24105g'), 'achievement', 'FE 24-105mm F4 G OSS', 1, '/product-badge/SEL24105G.png', NULL, '/product-badge/SEL24105G.png', 208),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2450g'), 'achievement', 'FE 24-50mm F2.8 G', 1, '/product-badge/SEL2450G.png', NULL, '/product-badge/SEL2450G.png', 209),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm'), 'achievement', 'FE 24-70mm F2.8 GM', 1, '/product-badge/SEL2470GM.png', NULL, '/product-badge/SEL2470GM.png', 210),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm2'), 'achievement', 'FE 24-70mm F2.8 GM II', 1, '/product-badge/SEL2470GM2.png', NULL, '/product-badge/SEL2470GM2.png', 211),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2870gm'), 'achievement', 'FE 28-70mm F2 GM', 1, '/product-badge/SEL2870GM.png', NULL, '/product-badge/SEL2870GM.png', 212),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50150gm'), 'achievement', 'FE 50-150 mm.F2 GM', 1, '/product-badge/SEL50150GM.png', NULL, '/product-badge/SEL50150GM.png', 213),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selc1635g'), 'achievement', 'FE C 16-35mm T3.1 G', 1, '/product-badge/SELC1635G.png', NULL, '/product-badge/SELC1635G.png', 214),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp1635g'), 'achievement', 'FE PZ 16-35mm F4 G', 1, '/product-badge/SELP1635G.png', NULL, '/product-badge/SELP1635G.png', 215),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp28135g'), 'achievement', 'FE PZ 28-135mm F4 G OSS', 1, '/product-badge/SELP28135G.png', NULL, '/product-badge/SELP28135G.png', 216),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635z'), 'achievement', 'Vario-Tessar T* FE 16-35mm F4 ZA OSS', 1, '/product-badge/SEL1635Z.png', NULL, '/product-badge/SEL1635Z.png', 217),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470z'), 'achievement', 'Vario-Tessar T* FE 24-70mm F4 ZA OSS', 1, '/product-badge/SEL2470Z.png', NULL, '/product-badge/SEL2470Z.png', 218),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70350g'), 'achievement', 'E 70-350mm F4.5-6.3 G OSS', 1, '/product-badge/SEL70350G.png', NULL, '/product-badge/SEL70350G.png', 301),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400mc'), 'achievement', 'FE 100-400 mm.F4.5 GM OSS', 1, '/product-badge/SEL100400MC.png', NULL, '/product-badge/SEL100400MC.png', 302),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400gm'), 'achievement', 'FE 100-400mm F4.5-5.6 GM OSS', 1, '/product-badge/SEL100400GM.png', NULL, '/product-badge/SEL100400GM.png', 303),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel200600g'), 'achievement', 'FE 200-600mm F5.6-6.3 G OSS', 1, '/product-badge/SEL200600G.png', NULL, '/product-badge/SEL200600G.png', 304),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel300f28gm'), 'achievement', 'FE 300mm F2.8 GM OSS', 1, '/product-badge/SEL300F28GM.png', NULL, '/product-badge/SEL300F28GM.png', 305),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400800g'), 'achievement', 'FE 400-800 mm.F6.3-8 G OSS', 1, '/product-badge/SEL400800G.png', NULL, '/product-badge/SEL400800G.png', 306),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400f28gm'), 'achievement', 'FE 400mm F2.8 GM OSS', 1, '/product-badge/SEL400F28GM.png', NULL, '/product-badge/SEL400F28GM.png', 307),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel600f40gm'), 'achievement', 'FE 600mm F4 GM OSS', 1, '/product-badge/SEL600F40GM.png', NULL, '/product-badge/SEL600F40GM.png', 308),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm'), 'achievement', 'FE 70-200mm F2.8 GM OSS', 1, '/product-badge/SEL70200GM.png', NULL, '/product-badge/SEL70200GM.png', 309),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm2'), 'achievement', 'FE 70-200mm F2.8 GM OSS II', 1, '/product-badge/SEL70200GM2.png', NULL, '/product-badge/SEL70200GM2.png', 310),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g'), 'achievement', 'FE 70-200mm F4 G OSS', 1, '/product-badge/SEL70200G.png', NULL, '/product-badge/SEL70200G.png', 311),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g2'), 'achievement', 'FE 70-200mm F4 Macro G OSS II', 1, '/product-badge/SEL70200G2.png', NULL, '/product-badge/SEL70200G2.png', 312),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-1m2'), 'achievement', 'Alpha 1 II', 1, '/product-badge/ILCE-1M2.png', NULL, '/product-badge/ILCE-1M2.png', 401),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-9m3'), 'achievement', 'Alpha 9 III', 1, '/product-badge/ILCE-9M3.png', NULL, '/product-badge/ILCE-9M3.png', 402),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7rm5'), 'achievement', 'Alpha 7R V', 1, '/product-badge/ILCE-7RM5.png', NULL, '/product-badge/ILCE-7RM5.png', 403),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m5'), 'achievement', 'Alpha 7 V', 1, '/product-badge/ILCE-7M5.png', NULL, '/product-badge/ILCE-7M5.png', 404),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m4'), 'achievement', 'Alpha 7 IV', 1, '/product-badge/ILCE-7M4.png', NULL, '/product-badge/ILCE-7M4.png', 405),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m3'), 'achievement', 'Alpha 7 III', 1, '/product-badge/ILCE-7M3.png', NULL, '/product-badge/ILCE-7M3.png', 406),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cm2'), 'achievement', 'Alpha 7C II', 1, '/product-badge/ILCE-7CM2.png', NULL, '/product-badge/ILCE-7CM2.png', 407),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7c'), 'achievement', 'Alpha 7C', 1, '/product-badge/ILCE-7C.png', NULL, '/product-badge/ILCE-7C.png', 408),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cr'), 'achievement', 'Alpha 7CR', 1, '/product-badge/ILCE-7CR.png', NULL, '/product-badge/ILCE-7CR.png', 409),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7sm3'), 'achievement', 'Alpha 7S III', 1, '/product-badge/ILCE-7SM3.png', NULL, '/product-badge/ILCE-7SM3.png', 410),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'bronze', 'Portrait Master Bronze', 2, '/quest-badge/portrait-bronze.png', NULL, '/quest-badge/portrait-bronze.png', 1001),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'silver', 'Portrait Master Silver', 3, '/quest-badge/portrait-silver.png', NULL, '/quest-badge/portrait-silver.png', 1002),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'gold', 'Portrait Master Gold', 4, '/quest-badge/portrait-gold.png', NULL, '/quest-badge/portrait-gold.png', 1003),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'bronze', 'Wide Architect Bronze', 3, '/quest-badge/wide-bronze.png', NULL, '/quest-badge/wide-bronze.png', 1011),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'silver', 'Wide Architect Silver', 4, '/quest-badge/wide-silver.png', NULL, '/quest-badge/wide-silver.png', 1012),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'gold', 'Wide Architect Gold', 5, '/quest-badge/wide-gold.png', NULL, '/quest-badge/wide-gold.png', 1013),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'bronze', 'The Visionary Bronze', 2, '/quest-badge/the-visionary-bronze.png', NULL, '/quest-badge/the-visionary-bronze.png', 1021),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'silver', 'The Visionary Silver', 3, '/quest-badge/the-visionary-silver.png', NULL, '/quest-badge/the-visionary-silver.png', 1022),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'gold', 'The Visionary Gold', 4, '/quest-badge/the-visionary-gold.png', NULL, '/quest-badge/the-visionary-gold.png', 1023),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'achievement', 'Trinity Master', 3, '/quest-badge/trinity-master.png', NULL, '/quest-badge/trinity-master.png', 1031),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-junior'), 'achievement', 'Trinity Junior', 3, '/quest-badge/trinity-junior.png', NULL, '/quest-badge/trinity-junior.png', 1041),
  ((SELECT id FROM badge_rules WHERE badge_code = 'all-rounder'), 'achievement', 'All Rounder', 3, '/quest-badge/all-around.png', NULL, '/quest-badge/all-around.png', 1051),
  ((SELECT id FROM badge_rules WHERE badge_code = 'f2-master'), 'achievement', 'F2 Master', 2, '/quest-badge/f2-master.png', NULL, '/quest-badge/f2-master.png', 1061),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-magnifier'), 'achievement', 'The Magnifier', 1, '/quest-badge/the-magnifier.png', NULL, '/quest-badge/the-magnifier.png', 1071);

DELETE FROM badge_rule_conditions
WHERE badge_rule_id IN (SELECT id FROM badge_rules WHERE badge_code IN ('product-sel100m28gm', 'product-sel90m28g', 'product-sel30m35', 'product-sel135f18gm', 'product-sel14f18gm', 'product-sel16f18g', 'product-sel20f18g', 'product-sel24f14gm', 'product-sel24f28g', 'product-sel35f14gm', 'product-sel35f18f', 'product-sel50f12gm', 'product-sel50f14gm', 'product-sel50m28', 'product-sel85f14gm', 'product-sel85f14gm2', 'product-sel1655g', 'product-sel55210', 'product-selp18110g', 'product-sel1625g', 'product-sel1635gm', 'product-sel1635gm2', 'product-sel2070g', 'product-sel24105g', 'product-sel2450g', 'product-sel2470gm', 'product-sel2470gm2', 'product-sel2870gm', 'product-sel50150gm', 'product-selc1635g', 'product-selp1635g', 'product-selp28135g', 'product-sel1635z', 'product-sel2470z', 'product-sel70350g', 'product-sel100400mc', 'product-sel100400gm', 'product-sel200600g', 'product-sel300f28gm', 'product-sel400800g', 'product-sel400f28gm', 'product-sel600f40gm', 'product-sel70200gm', 'product-sel70200gm2', 'product-sel70200g', 'product-sel70200g2', 'product-ilce-1m2', 'product-ilce-9m3', 'product-ilce-7rm5', 'product-ilce-7m5', 'product-ilce-7m4', 'product-ilce-7m3', 'product-ilce-7cm2', 'product-ilce-7c', 'product-ilce-7cr', 'product-ilce-7sm3', 'portrait-master', 'wide-architect', 'the-visionary', 'trinity-master', 'trinity-junior', 'all-rounder', 'f2-master', 'the-magnifier'));
INSERT INTO badge_rule_conditions (
  badge_rule_id, condition_label, match_type, required_count, sony_skus
)
VALUES
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100m28gm'), 'Own SEL100M28GM', 'any', 1, '["SEL100M28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel90m28g'), 'Own SEL90M28G', 'any', 1, '["SEL90M28G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel30m35'), 'Own SEL30M35', 'any', 1, '["SEL30M35"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel135f18gm'), 'Own SEL135F18GM', 'any', 1, '["SEL135F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel14f18gm'), 'Own SEL14F18GM', 'any', 1, '["SEL14F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel16f18g'), 'Own SEL16F18G', 'any', 1, '["SEL16F18G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel20f18g'), 'Own SEL20F18G', 'any', 1, '["SEL20F18G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f14gm'), 'Own SEL24F14GM', 'any', 1, '["SEL24F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24f28g'), 'Own SEL24F28G', 'any', 1, '["SEL24F28G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f14gm'), 'Own SEL35F14GM', 'any', 1, '["SEL35F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel35f18f'), 'Own SEL35F18F', 'any', 1, '["SEL35F18F"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f12gm'), 'Own SEL50F12GM', 'any', 1, '["SEL50F12GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50f14gm'), 'Own SEL50F14GM', 'any', 1, '["SEL50F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50m28'), 'Own SEL50M28', 'any', 1, '["SEL50M28"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm'), 'Own SEL85F14GM', 'any', 1, '["SEL85F14GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel85f14gm2'), 'Own SEL85F14GM2', 'any', 1, '["SEL85F14GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1655g'), 'Own SEL1655G', 'any', 1, '["SEL1655G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel55210'), 'Own SEL55210', 'any', 1, '["SEL55210"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp18110g'), 'Own SELP18110G', 'any', 1, '["SELP18110G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1625g'), 'Own SEL1625G', 'any', 1, '["SEL1625G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm'), 'Own SEL1635GM', 'any', 1, '["SEL1635GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635gm2'), 'Own SEL1635GM2', 'any', 1, '["SEL1635GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2070g'), 'Own SEL2070G', 'any', 1, '["SEL2070G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel24105g'), 'Own SEL24105G', 'any', 1, '["SEL24105G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2450g'), 'Own SEL2450G', 'any', 1, '["SEL2450G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm'), 'Own SEL2470GM', 'any', 1, '["SEL2470GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470gm2'), 'Own SEL2470GM2', 'any', 1, '["SEL2470GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2870gm'), 'Own SEL2870GM', 'any', 1, '["SEL2870GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel50150gm'), 'Own SEL50150GM', 'any', 1, '["SEL50150GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selc1635g'), 'Own SELC1635G', 'any', 1, '["SELC1635G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp1635g'), 'Own SELP1635G', 'any', 1, '["SELP1635G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-selp28135g'), 'Own SELP28135G', 'any', 1, '["SELP28135G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel1635z'), 'Own SEL1635Z', 'any', 1, '["SEL1635Z"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel2470z'), 'Own SEL2470Z', 'any', 1, '["SEL2470Z"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70350g'), 'Own SEL70350G', 'any', 1, '["SEL70350G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400mc'), 'Own SEL100400MC', 'any', 1, '["SEL100400MC"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel100400gm'), 'Own SEL100400GM', 'any', 1, '["SEL100400GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel200600g'), 'Own SEL200600G', 'any', 1, '["SEL200600G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel300f28gm'), 'Own SEL300F28GM', 'any', 1, '["SEL300F28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400800g'), 'Own SEL400800G', 'any', 1, '["SEL400800G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel400f28gm'), 'Own SEL400F28GM', 'any', 1, '["SEL400F28GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel600f40gm'), 'Own SEL600F40GM', 'any', 1, '["SEL600F40GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm'), 'Own SEL70200GM', 'any', 1, '["SEL70200GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200gm2'), 'Own SEL70200GM2', 'any', 1, '["SEL70200GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g'), 'Own SEL70200G', 'any', 1, '["SEL70200G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-sel70200g2'), 'Own SEL70200G2', 'any', 1, '["SEL70200G2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-1m2'), 'Own ILCE-1M2', 'any', 1, '["ILCE-1M2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-9m3'), 'Own ILCE-9M3', 'any', 1, '["ILCE-9M3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7rm5'), 'Own ILCE-7RM5', 'any', 1, '["ILCE-7RM5"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m5'), 'Own ILCE-7M5', 'any', 1, '["ILCE-7M5"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m4'), 'Own ILCE-7M4', 'any', 1, '["ILCE-7M4"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7m3'), 'Own ILCE-7M3', 'any', 1, '["ILCE-7M3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cm2'), 'Own ILCE-7CM2', 'any', 1, '["ILCE-7CM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7c'), 'Own ILCE-7C', 'any', 1, '["ILCE-7C"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7cr'), 'Own ILCE-7CR', 'any', 1, '["ILCE-7CR"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'product-ilce-7sm3'), 'Own ILCE-7SM3', 'any', 1, '["ILCE-7SM3"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'portrait-master'), 'Collect eligible Portrait Master models', 'min_count', 4, '["SEL35F14GM","SEL50F14GM","SEL50F12GM","SEL85F14GM","SEL85F14GM2","SEL100M28GM","SEL135F18GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'wide-architect'), 'Collect eligible Wide Architect models', 'min_count', 5, '["SEL1224GM","SEL14F18GM","SEL16F18G","SEL20F18G","SEL1625G","SEL1635GM","SEL1635GM2","SEL1635Z","SEL2470GM","SEL2470GM2","SEL2450G","SELC1635G","SEL1655G","SEL2070G","SEL24105G","SEL2470Z","SEL24F14GM","SEL24F28G","SEL2870GM","SEL35F14GM","SEL35F18F","SELP1635G","SELP18110G","SELP28135G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-visionary'), 'Collect eligible The Visionary models', 'min_count', 4, '["SEL100400GM","SEL400800G","SEL200600G","SEL300F28GM","SEL400F28GM","SEL600F40GM","SEL70350G","SEL55210","SEL100400MC"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 16-35 GM family model', 'any', 1, '["SEL1635GM","SEL1635GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 24-70 GM family model', 'any', 1, '["SEL2470GM","SEL2470GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-master'), 'Own one 70-200 GM family model', 'any', 1, '["SEL70200GM","SEL70200GM2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'trinity-junior'), 'Own all Trinity Junior models', 'all', 3, '["SEL2450G","SEL1625G","SEL70200G2"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'all-rounder'), 'Own any three All Rounder models', 'min_count', 3, '["SEL2070G","SELP1635G","SEL1635Z","SEL70200G"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'f2-master'), 'Own both F2 Master models', 'all', 2, '["SEL2870GM","SEL50150GM"]'),
  ((SELECT id FROM badge_rules WHERE badge_code = 'the-magnifier'), 'Own any one macro model', 'any', 1, '["SEL100M28GM","SEL90M28G","SEL50M28","SEL30M35"]');

COMMIT;
